version: '3.8'

services:
  bot:
    container_name: bm-bot-production
    build:
      context: ./bot
      dockerfile: ./compose/Dockerfile
    volumes:
      - ./bot:/go/src/app
    restart: unless-stopped

  backend:
    container_name: bm-nest-production
    depends_on:
      - bot
    build:
      context: ./server
      dockerfile: ./compose/Dockerfile
    ports:
        - 80:8000
    env_file:
      - ./server/.env.production
    volumes:
        - ./server:/usr/src/app
        - /usr/src/app/node_modules