version: '3.8'

services:
  postgres:
    container_name: bm-server-local
    ports:
      - 5432:5432
    image: postgres:15.5
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/postgresql/data
    